drop table if exists public.templates;

create table
  public.templates (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    template_id text null,
    template_name text null,
    police_dpt text null,
    client_code bigint,
    type text,
    created_by text null,
    last_date_modified timestamp with time zone not null default now(),
    last_modified_by text null,
    cc_recipients text null,
    active text null,
    subject text null,
    message text null,
    constraint templates_pkey primary key (id)
  ) tablespace pg_default;