
create table
  public.templates (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    template_id text not null,
    template_name text not null,
    police_dpt text not null,
    client_code bigint,
    type text not null,
    created_by text not null,
    last_date_modified timestamp with time zone not null default now(),
    last_modified_by text not null,
    cc_recipients text not null,
    active text not null,
    subject text not null,
    message text not null,
    constraint templates_pkey primary key (id)
  ) tablespace pg_default;