drop table if exists public.rules;

create table
  public.rules (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    rule_id text not null,
    police_dpt text not null,
    client_code bigint not null,
    created_by text not null,
    last_date_modified timestamp with time zone not null default now(),
    last_modified_by text not null,
    delay text not null,
    status text not null,
    if_logic text not null,
    then_logic text not null,
    constraint rules_pkey primary key (id)
  ) tablespace pg_default;